### ISSUE TITLE
Forwarder Agent grabs random port. Sometimes that port is important and not-ephemeral.

### ISSUE THREAD

**Issue by ameowlia** [cloudfoundry/loggregator-agent-release#134]
## What we expect to happen
Forwarder-agent only uses ephemeral ports to talk to the syslog agent.

## What actually happened
Forwarder-agent uses non-ephemeral ports. In our case it grabbed `8080` and stopped gorouter from starting!

## Reproduction Steps
1. Get a CF 
2. Ssh onto a vm with forwarder agent
3. Run `netstat -tnap | grep 3460 | grep forward`
   `tcp        0      0 127.0.0.1:42142         127.0.0.1:3460          ESTABLISHED 29373/forwarder-age`
4. Note the port that the forwarder agent is connecting on (42142)
5. Run `monit restart loggr-forwarder-agent`
6. Check the port again. `netstat -tnap | grep 3460 | grep forward` (4640)
   `tcp        0      0 127.0.0.1:4640          127.0.0.1:3460          ESTABLISHED 30082/forwarder-age`
7. Do it a bunch of times and you will see it grabs non-ephemeral port.

**Comment by acrmp** [comment]
@ameowlia Can you share the stemcell version and the version of loggregator-agent-release?

We've tried reproducing this on xenial, bionic and jammy without success so far.

**Comment by acrmp** [comment]
I could reproduce it specifically on a router VM.

I believe it's due to this:
https://github.com/cloudfoundry/routing-release/blob/b70c6a59c5fe06b88f9c081d20fb05fe42b848f9/jobs/gorouter/spec#L447-L449

**Comment by geofffranks** [comment]
Agreed. We will resolve there. Thanks for digging in, sorry for the false alarm
