### ISSUE TITLE
`loggr-syslog-agent` config missing `drain_ca_cert` in examples

### ISSUE THREAD

**Issue by MirahImage** [cloudfoundry/loggregator-agent-release#231]
The field `drain_ca_cert` is missing from the `loggr-syslog-agent` config example.
https://github.com/cloudfoundry/loggregator-agent-release/blob/00b619faef7a8de51a222e82de6b5583c7daa8f5/docs/syslog-agent.md

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/loggregator-agent-release/pull/232

**Comment by Benjamintf1** [comment]
think that should be done now.
