### ISSUE TITLE
loggr-udp-forwarder consumption of cloud_controller

### ISSUE THREAD

**Issue by scottillogical** [cloudfoundry/loggregator-agent-release#25]
Hey folks
loggr-udp-forwarder declares that it consumes cloud_controller  https://github.com/cloudfoundry/loggregator-agent-release/blob/develop/jobs/loggr-udp-forwarder/spec#L17 
However, I couldn't find any place in the source code where it uses that bosh link https://github.com/cloudfoundry/loggregator-agent-release/tree/develop/src/cmd/udp-forwarder

Am I missing something or could this consumption be removed?   I'm asking because we actually use diego + loggregator in a environment without cloud controller. 

Thanks!

**Comment by MasslessParticle** [comment]
Thanks! It looks like this is indeed a bug. We've dropped a story to address it.

**Comment by pianohacker** [comment]
This has been fixed; closing.
