### ISSUE TITLE
CAs for syslog-drain mtls feature can be overwritten

### ISSUE THREAD

**Issue by fhambrec** [cloudfoundry/loggregator-agent-release#286]
When we tested the use of CAs for syslog-drains in our systems, we found a behaviour in the cloud controller's recently introduced v5 bindings endpoint which we think is unintended. 

**Scenario to recreate the issue**

Create 2 user-provided-services: One with CA and one without CA using the same drain-url.
bind each user-provided-service to a different application (app-a, app-b)
Check the bindings on the scheduler in the loggr-syslog-binding-cache job: 
```
scheduler:/var/vcap/jobs/loggr-syslog-binding-cache/config/certs
# curl -s --cacert api_ca.crt --key api_client.key --cert api_client.crt -k api_endpoint/internal/v5/syslog_drain_urls
    
  "results": [
    {
      "url": "syslog-tls://example.com:5140",
      "credentials": [
        {
          "cert": "-----BEGIN CERTIFICATE-----\ntest...cert\n-----END CERTIFICATE-----\n",
          "key": "-----BEGIN CERTIFICATE-----\ntest...key\n-----END CERTIFICATE-----\n",
          "ca": "-----BEGIN CERTIFICATE-----\ntest...ca\n-----END CERTIFICATE-----\n",
          "apps": [
            {
              "hostname": "cf-loggregator-test.app-a",
              "app_id": "app-id-a"
            },
            {
              "hostname": "cf-loggregator-test-app-b",
              "app_id": "app-id-b"
            }
          ]
        }
      ]
    }
  ] 
```

With this setup, an application that has no CA configured via its user-provided-service is able to send logs to the configured syslog-drain-url. In general it is possible to overwrite CAs of other users' syslog-drains.

Most likely this issue can be fixed by adjusting the json transformation or the query in the [cloud controller ng coding](https://github.com/cloudfoundry/cloud_controller_ng/blob/c7da033de881969f008618b2d3b847058d3ae575/app/controllers/internal/syslog_drain_urls_controller.rb#L84). 

This issue can partly be fixed in the cloud controller. Since the binding-cache depends on the json returned by the cloud controller (see [here](https://github.com/cloudfoundry/loggregator-agent-release/blob/94f119c3a2d792c21a62920ab85b7eb11796790a/src/pkg/binding/poller.go#L28)) we would like to raise awareness for this topic also in this repository.

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/cf-deployment/blob/cfa42d657bd40b0c56af6300275dc20552480806/cf-deployment.yml#L2874-L2876

https://github.com/cloudfoundry/capi-release/releases/tag/1.152.0

Looks like we resolved it? 

Let me know how that goes, otherwise I'm going to close this like, next week.
