### ISSUE TITLE
syslog TLS drains incorrectly setting limited ciphers

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/loggregator-agent-release#34]
we have found yet another BIG change in the syslog support from the cf-syslog-agent to the new loggregator-agent that has broken another one of our customers.    

In the cf-syslog-release the TLS connections was setup like this …
https://github.com/cloudfoundry/cf-syslog-drain-release/blob/0e61ebe9a6aaa87a6bf036f41c8a7472d56bf73f/src/adapter/internal/egress/tls.go#L35
Which is basically an empty config with ONLY skipCertVerify.

but in the new agent code.  it’s completely different and ends up using this config …
https://github.com/cloudfoundry/tlsconfig/blob/master/config.go#L115
We are now seeing issues with wrong cipher suites!   as the client to send syslog out is the code using “internalServiceDefaults” and setting a very limited number of ciphers ?

https://github.com/cloudfoundry/loggregator-agent-release/blob/develop/src/cmd/syslog-agent/app/syslog_agent.go#L56
https://github.com/cloudfoundry/loggregator-agent-release/blob/166d48b4e2bbc185f3911a7b8ab9c216812e738f/src/cmd/syslog-agent/app/syslog_agent.go#L114

This change has broken some previous functionality.

I propose that you change this code ...

diff --git a/src/pkg/egress/syslog/writer_factory.go b/src/pkg/egress/syslog/writer_factory.go
index 5b504ac..51f6fc3 100644
--- a/src/pkg/egress/syslog/writer_factory.go
+++ b/src/pkg/egress/syslog/writer_factory.go
@@ -51,7 +51,7 @@ func (f WriterFactory) NewWriter(
                return NewTLSWriter(
                        urlBinding,
                        netConf,
-                       f.tlsConfig,
+                       &tls.Config{ InsecureSkipVerify: f.tlsConfig.InsecureSkipVerify, },
                        f.egressMetric,
                ), nil
        default:

**Comment by pianohacker** [comment]
We'd like to make this configurable, with a set of ciphers that defaults to the external defaults. That should allow you to expand the list to a very permissive set. There will be a special parameter that can be added to app/aggregate drains to restrict to the internal cipher suites, which we've added to ensure that communication with Log Cache can still be correctly secured.

**Comment by pianohacker** [comment]
This configuration will be added in version 6.1.0, which we will be releasing within the next two weeks.

**Comment by pianohacker** [comment]
Verified working, the team will be cutting a release today or tomorrow.

**Comment by pianohacker** [comment]
This has shipped in Loggregator Agent 6.1.0.
