### ISSUE TITLE
syslog drains added new tags to log messages that were not there before

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/loggregator-agent-release#35]
the new agent is adding and sending a lot more data per line by adding a bunch of “tags” this was not announced as a breaking change.  for many of our customers this additional data can cause issues with the the licensing limits to the amount of log data being sent.  these tags were not included in the cf-syslog-drain release log lines but now are.  I see no way to turn them off to reduce this “noise” for our customers.   we really need to have someway to turn this additional tags information off to get the log lines looking exactly as they were with cf-syslog-drain-release

https://github.com/cloudfoundry/cf-syslog-drain-release/blob/develop/src/adapter/internal/egress/tcp.go#L109

How the rfc5424 messages were created in cf-syslog-drain (note no StructuredData!)

Code to convert this to the string being sent out is here …
https://github.com/cloudfoundry-incubator/rfc5424/blob/master/marshal.go#L148

VS the new code which is adding the structuredData even for the log lines.

https://github.com/cloudfoundry/loggregator-agent-release/blob/develop/src/pkg/egress/syslog/rfc5424.go#L146

We need to have the ability to turn this structured data off for log type messages or it should be turned off by default to match the previous functionality.

**Comment by pianohacker** [comment]
We'll be adding a per-drain opt-out for these tags, via a query parameter on the drain URL. There's been a number of commercial consumers who've already made use of this, so we can't turn it off by default, but we want to offer app developers/operators the individual choice between the extra metadata on these logs and saving bandwidth.

This opt-out will be added in version 6.1.0, which we will be releasing within the next two weeks.

**Comment by ranjith-hub-Hash4** [comment]
@pianohacker can you please let us know when 6.1.0 is available and how to add the toggle to false?

**Comment by ranjith-rajaram** [comment]
@pianohacker - Can you please inform me when 6.1.0 is available and how to add the toggle to false?

**Comment by gvolpe1968** [comment]
@pianohacker : any news on this item? thx

**Comment by pianohacker** [comment]
There have been some delays on our end due to internal support obligations, apologies. The team is finishing delivery of the work, a release should be forthcoming very soon.

**Comment by pianohacker** [comment]
We've validated that this is working, and will be releasing it once #34 is also complete.

**Comment by pianohacker** [comment]
To clarify how this will work, it will be possible to opt out of tags-as-structured-data on app and aggregate drains by appending `?disable-metadata=true` to the drain URL.

**Comment by ranjith-rajaram** [comment]
@pianohacker - When will this get released, any dates? 
Once this is released will it take IBM 2 weeks to test and validate, correct?

**Comment by pianohacker** [comment]
@ranjith-rajaram The release of this work was pending the work on #34 , which is now done. I need to test that, then a release should be headed out the door shortly.

**Comment by pianohacker** [comment]
This has shipped in Loggregator Agent 6.1.0.
