### ISSUE TITLE
udp-forwarder debug port should be configurable

### ISSUE THREAD

**Issue by ameowlia** [cloudfoundry/loggregator-agent-release#44]
## What
As a CF operator
I want to know which ports system components are using on the TCP Router VM
So that I can make sure they don't overlap with tcp router ports
So that my tcp router doesn't silently break. See issue [here](https://github.com/cloudfoundry/routing-release/issues/184).

### Steps to reproduce
1. Deploy with the udp-forwarder on any VM
2. ssh onto that VM
3. run `netstat -tlpn | grep udp-forwarder`
4. note the port it is running on
5. run `monit restart loggr-udp-forwarder`
6. run `netstat -tlpn | grep udp-forwarder`
7. see that the port here does not match the port from step 4

### Expected
I want to be able to set the debug port as a bosh property and to have it respected.

### Actual
The debug port is any random open port. 

### Technical Details

`jobs/loggr-udp-forwarder/templates/bpm.yml.erb` [link](https://github.com/cloudfoundry/loggregator-agent-release/blob/acfbb6b015d897c11f715ac9e1a226eb5b96875c/jobs/loggr-udp-forwarder/templates/bpm.yml.erb#L8-L29)
* here a bunch of env vars are set that get passed to the udp-forwarder
* METRICS_PORT and UDP_PORT are set based on bosh properties
* No DEBUG_PORT is mentioned

`src/cmd/udp-forwarder/app/config.go ` [link](https://github.com/cloudfoundry/loggregator-agent-release/blob/acfbb6b015d897c11f715ac9e1a226eb5b96875c/src/cmd/udp-forwarder/app/config.go#L21-L28)
* here the env vars are read into the golang config that the udp-forwarder uses
* It reads in DEBUG_PORT and UDP_PORT.
* Given that DEBUG_PORT is never set to anything in the `bpm.yml` this will default to 0.
* Note that METRICS_PORT is not read-in here. I think this is a _different_ bug that it always uses [this default value](https://github.com/cloudfoundry/loggregator-agent-release/blob/acfbb6b015d897c11f715ac9e1a226eb5b96875c/src/cmd/udp-forwarder/app/config.go#L38) and not the bosh property. I have not tested this though.
 

Then in the logs it says 
```
Config.DebugPort        int     DEBUG_PORT                        false      0.
```
This leads me to believe debug_port is started with port 0, which seems to mean that it just choses a random (ephemeral?) port.

I will submit a PR for this soon.

**Comment by ameowlia** [comment]
Per this [doc](https://github.com/cloudfoundry/routing-release/commit/83448037836e6f81a0afe3fdef2b2ac5bbf33c7d), we should try to have the default port be **14830**. If that is impossible, please update said doc.

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/loggregator-agent-release/releases/tag/v6.0.3
