### ISSUE TITLE
`health_port` property no longer used

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry/loggregator-agent-release#5]
Since the health endpoint metrics were moved to use expvar the health endpoint is served on the pprof port. The health port was not cleaned up from the bosh release or the implementation as part of that change and should be removed to avoid confusion.

https://github.com/cloudfoundry/loggregator-agent-release/blob/develop/jobs/loggregator_agent/spec#L48-L50

**Comment by jtuchscherer** [comment]
Fixed
