### ISSUE TITLE
Doppler link should be required

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry/loggregator-agent-release#6]
The BPM config for loggregator agent requires the doppler link, however the BOSH job spec still says its optional: https://github.com/cloudfoundry/loggregator-agent-release/blob/develop/jobs/loggregator_agent/spec#L14

**Comment by jtuchscherer** [comment]
This appears to be fixed in this commit: 
https://github.com/cloudfoundry/loggregator-agent-release/commit/234e5ff93a2b9669c886bca839701919f6431aff#diff-fb2ff30bc988edf7f3eb98e0fca11154
