### ISSUE TITLE
Incorrect syslog drain URLs can spam operators with unhelpful messages

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/loggregator-agent-release#81]
### Steps to reproduce
1. create a user provided service with an invalid host, e.g.:
    ```bash
    cf create-user-provided-service drain-3 -l syslog:hello.com
    ```
2. bind that service to an app

### Expected

**1. The syslog agent should ignore syslog drain URLs that don't have a supported scheme before logging an error related to incorrect hosts**
The syslog agent currently skips any syslog drain URLs that do not have one of these schemes: `syslog`, `syslog-tls`, and `https`. However, the current logic checks for a hostname first, which may log lots of errors given the way some other components reuse the syslog drain (with different schemes).

**2. A good error message in the syslog agent logs**
If an error is going to be output in the syslog agent logs I would expect it to be descriptive about the fact that the error is coming from a syslog drain, and what the offending syslog drain URL is. If we could find some way to not be very spammy about the error that would be nice too.

### Actual

If one were to tail the `loggr-syslog-agent` error logs via:
```bash
bosh ssh ANY_VM
sudo -i
tail -F /var/vcap/sys/log/loggr-syslog-agent/loggr-syslog-agent.stderr.log
```
you will see a very confusing, spammy output that gives no indication that the drain is a user provided service, or even what the URL is that is causing such a problem:
```
2022-03-18T16:28:54.232943335Z failed to parse host for drain URL: invalid URL, detected no host
2022-03-18T16:28:54.232943335Z failed to parse host for drain URL: invalid URL, detected no host
2022-03-18T16:28:54.232943335Z failed to parse host for drain URL: invalid URL, detected no host
...
```

**Comment by ctlong** [comment]
https://github.com/cloudfoundry/loggregator-agent-release/blob/3e1f64de04f50bc7679fbe874f752d8552ab9ba2/src/pkg/ingress/bindings/filtered_binding_fetcher.go#L63-L96

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/loggregator-agent-release/pull/88 fixed.
